backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

display_url: https://traci.netlify.com

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

media_library:
  name: uploadcare
  config:
    publicKey: ceb8dff5c2ef31fd1a2e

collections:
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "About" # Used in the UI
    folder: "public/content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "about" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter. 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "About Text", name: "body", widget: "markdown"}
      - {label: "Profile Picture", name: "profile", widget: "image"}

  - name: "portfolio"
    label: "Portfolio Projects"
    folder: "public/content/portfolio"
    slug: "{{year}}-{{month}}-{{day}}--{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: Image
        name: "image_url"
        widget: "image"

  - name: "sketches"
    label: "Sketches"
    folder: "public/content/sketches"
    slug: "{{year}}-{{month}}-{{day}}--{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: Image
        name: "image_url"
        widget: "image"
